name: Python Package using Conda Updated

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
      
    - name: Add conda to system path
      run: |
        echo "$CONDA/bin" >> $GITHUB_PATH

    - name: Install libarchive dependency (for libmamba solver)
      run: sudo apt-get install -y libarchive-dev

    - name: Update Conda and Set Classic Solver
      run: |
        conda update -n base -c defaults conda
        conda config --set solver classic

    - name: Install dependencies from environment.yml
      run: |
        conda env update --file environment.yml --name base

    - name: Lint with flake8
      run: |
        conda install -y flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install -y pytest
        pytest
